Publish updates from master  (#15204)
Updates from master

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -1,8 +1,10 @@
 name: publish
 
 on:
+  workflow_dispatch:
   push:
     branches:
+      - lab
       - master
       - published
 
@@ -26,6 +28,13 @@ jobs:
             DOCS_S3_CONFIG="_website-config-docs.json"
             DOCS_LAMBDA_FUNCTION_CACHE="arn:aws:lambda:us-east-1:710015040892:function:docs-cache-invalidator"
             DOCS_SLACK_MSG="Successfully published docs. https://docs.docker.com/"
+          elif [ "${{ github.ref }}" = "refs/heads/lab" ]; then
+            DOCS_S3_BUCKET=""
+            DOCS_LAMBDA_FUNCTION_CACHE=""
+            DOCS_S3_CONFIG="_website-config-docs-lab.json"
+          else
+            echo >&2 "ERROR: unknown branch ${{ github.ref }}"
+            exit 1
           fi
           echo "JEKYLL_ENV=$JEKYLL_ENV" >> $GITHUB_ENV
           echo "DOCS_AWS_REGION=$DOCS_AWS_REGION" >> $GITHUB_ENV
@@ -69,6 +78,7 @@ jobs:
           AWS_S3_CONFIG: ${{ env.DOCS_S3_CONFIG }}
       -
         name: Invalidate docs website cache
+        if: ${{ env.DOCS_LAMBDA_FUNCTION_CACHE != '' }}
         uses: docker/bake-action@v2
         with:
           targets: aws-lambda-invoke
@@ -81,5 +91,6 @@ jobs:
           AWS_LAMBDA_FUNCTION: ${{ env.DOCS_LAMBDA_FUNCTION_CACHE }}
       -
         name: Send Slack notification
+        if: ${{ env.DOCS_SLACK_MSG != '' }}
         run: |
           curl -X POST -H 'Content-type: application/json' --data '{"text":"${{ env.DOCS_SLACK_MSG }}"}' ${{ secrets.SLACK_WEBHOOK }}
